name: Example repo dispatch

on:
  repository_dispatch:
    types: [promoteToStaging]

jobs:
  example-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received. Passed: ${{ github.event.client_payload.passed }}, failed: '${{ github.event.client_payload.failed }}'"