name: RaptorsMultiRenterDeals

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Select Environment"
        required: true
        type: choice
        default: "staging"
        options:
          - "staging"
          - "integration"

      building_template:
        description: "Select Building Name"
        required: true
        type: choice
        default: "Automation Property REN-5835"
        options:
          - "Automation Property REN-5835"
          - "exNYC, Multi renter deal, REN-5835"
          - "TG_engine_34806"

      building_id:
        description: "Custom building id (should be assigned to qa.test.landlord@securiti.io). Will override the building selected above"
        type: string

      init_type:
        description: "Init by"
        required: true
        type: choice
        default: "Landlord invite"
        options:
          - "Landlord invite"

      app_template_1:
        description: "Application #1: Status, FICO, SL Abuse Score, OFAC Alert, SSN, LastName, FirstName"
        required: true
        type: choice
        default: "Application Submitted, 825, JOSEPH, GILBERT, 666586249"
        options:
          - "Submitted, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Submitted, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Submitted, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Submitted, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Submitted, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Submitted, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Submitted, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Submitted, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "DocUpload, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "DocUpload, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "DocUpload, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "DocUpload, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "DocUpload, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "DocUpload, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "DocUpload, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "DocUpload, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "Created, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Created, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Created, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Created, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Created, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Created, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Created, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Created, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"

      app_template_2:
        description: "Application #2: Status, FICO, SL Abuse Score, OFAC Alert, SSN, LastName, FirstName"
        required: true
        type: choice
        default: "Application Submitted, JOSEPH, GILBERT, 666586249"
        options:
          - "Submitted, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Submitted, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Submitted, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Submitted, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Submitted, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Submitted, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Submitted, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Submitted, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "DocUpload, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "DocUpload, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "DocUpload, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "DocUpload, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "DocUpload, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "DocUpload, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "DocUpload, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "DocUpload, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "Created, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Created, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Created, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Created, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Created, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Created, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Created, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Created, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"

      app_template_3:
        description: "Application #3: Status, FICO, SL Abuse Score, OFAC Alert, SSN, LastName, FirstName"
        required: true
        type: choice
        default: "-"
        options:
          - "-"
          - "Submitted, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Submitted, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Submitted, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Submitted, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Submitted, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Submitted, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Submitted, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Submitted, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "DocUpload, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "DocUpload, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "DocUpload, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "DocUpload, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "DocUpload, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "DocUpload, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "DocUpload, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "DocUpload, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "Created, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Created, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Created, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Created, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Created, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Created, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Created, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Created, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"

      app_template_4:
        description: "Application #4: Status, FICO, SL Abuse Score, OFAC Alert, SSN, LastName, FirstName"
        required: true
        type: choice
        default: "-"
        options:
          - "-"
          - "Submitted, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Submitted, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Submitted, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Submitted, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Submitted, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Submitted, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Submitted, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Submitted, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "DocUpload, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "DocUpload, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "DocUpload, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "DocUpload, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "DocUpload, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "DocUpload, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "DocUpload, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "DocUpload, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "Created, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Created, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Created, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Created, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Created, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Created, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Created, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Created, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"

      app_template_5:
        description: "Application #5: Status, FICO, SL Abuse Score, OFAC Alert, SSN, LastName, FirstName"
        required: true
        type: choice
        default: "-"
        options:
          - "-"
          - "Submitted, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Submitted, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Submitted, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Submitted, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Submitted, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Submitted, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Submitted, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Submitted, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "DocUpload, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "DocUpload, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "DocUpload, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "DocUpload, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "DocUpload, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "DocUpload, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "DocUpload, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "DocUpload, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "Created, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Created, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Created, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Created, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Created, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Created, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Created, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Created, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"

      app_template_6:
        description: "Application #6: Status, FICO, SL Abuse Score, OFAC Alert, SSN, LastName, FirstName"
        required: true
        type: choice
        default: "-"
        options:
          - "-"
          - "Submitted, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Submitted, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Submitted, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Submitted, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Submitted, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Submitted, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Submitted, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Submitted, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "DocUpload, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "DocUpload, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "DocUpload, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "DocUpload, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "DocUpload, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "DocUpload, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "DocUpload, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "DocUpload, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"
          - "Created, fico_825, sl_390, ofac_true, 666586249, gilbert, joseph"
          - "Created, fico_770, sl_10, ofac_false, 666001464, qhpsz, nuiaafbhm"
          - "Created, fico_700, sl_0, ofac_false, 555555554, sstoragetest, laura"
          - "Created, fico_624, sl_10, ofac_false, 666015670, nekj, kiiuyrq"
          - "Created, fico_613, sl_10, ofac_false, 666044730, zvtyzb, qytzj"
          - "Created, fico_580, sl_750, ofac_false, 666000004, wedefnz, wngidw"
          - "Created, fico_364, sl_10, ofac_false, 666004357, pgvbmj, ygvc"
          - "Created, fico_-1, sl_10, ofac_false, 666011377, pnulvy, arjijl"

env:
  JSON_INPUT: ${{ github.event.inputs.movie_as_json }}
      
jobs:
  welcome-to-marvel:
    runs-on: ubuntu-latest
    steps:
      - name: set inputs as variables
        run: |
          echo -e "First_Movie=$(echo $JSON_INPUT | jq ".First_Movie")" >> $GITHUB_ENV
          echo -e "Second_Movie=$(echo $JSON_INPUT | jq ".Second_Movie")" >> $GITHUB_ENV
          echo -e "Third_Movie=$(echo $JSON_INPUT | jq ".Third_Movie")" >> $GITHUB_ENV
          echo -e "Fourth_Movie=$(echo $JSON_INPUT | jq ".Fourth_Movie")" >> $GITHUB_ENV
          echo -e "Fifth_Movie=$(echo $JSON_INPUT | jq ".Fifth_Movie")" >> $GITHUB_ENV
          echo -e "Sixth_Movie=$(echo $JSON_INPUT | jq ".Sixth_Movie")" >> $GITHUB_ENV
          echo -e "Seventh_Movie=$(echo $JSON_INPUT | jq ".Seventh_Movie")" >> $GITHUB_ENV
          echo -e "Eighth_Movie=$(echo $JSON_INPUT | jq ".Eighth_Movie")" >> $GITHUB_ENV
          echo -e "Ninth_Movie=$(echo $JSON_INPUT | jq ".Ninth_Movie")" >> $GITHUB_ENV
          echo -e "Tenth_Movie=$(echo $JSON_INPUT | jq ".Tenth_Movie")" >> $GITHUB_ENV
          echo -e "Eleventh_Movie=$(echo $JSON_INPUT | jq ".Eleventh_Movie")" >> $GITHUB_ENV
          echo -e "Twelfth_Movie=$(echo $JSON_INPUT | jq ".Twelfth_Movie")" >> $GITHUB_ENV
      
      - name: Print movies list
        run: |
          echo "First_Movie= ${{ env.First_Movie }}"
          echo "Second_Movie= ${{ env.Second_Movie }}"
          echo "Third_Movie= ${{ env.Third_Movie }}"
          echo "Fourth_Movie= ${{ env.Fourth_Movie }}"
          echo "Fifth_Movie= ${{ env.Fifth_Movie }}"
          echo "Sixth_Movie= ${{ env.Sixth_Movie }}"
          echo "Seventh_Movie= ${{ env.Seventh_Movie }}"
          echo "Eighth_Movie= ${{ env.Eighth_Movie }}"
          echo "Ninth_Movie= ${{ env.Ninth_Movie }}"
          echo "Tenth_Movie= ${{ env.Tenth_Movie }}"
          echo "Eleventh_Movie= ${{ env.Eleventh_Movie }}"
          echo "Twelfth_Movie= ${{ env.Twelfth_Movie }}"
