name: RaptorsMultiRenterDeals

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Select Environment"
        required: true
        type: choice
        default: "staging"
        options:
          - "staging"
          - "integration"

      building_template:
        description: "Select Building Name"
        required: true
        type: choice
        default: "Automation Property REN-5835"
        options:
          - "Automation Property REN-5835"
          - "exNYC, Multi renter deal, REN-5835"
          - "TG_engine_34806"

      building_id:
        description: "Custom building id (should be assigned to qa.test.landlord@securiti.io). Will override the building selected above"
        type: string

      init_type:
        description: "Init by"
        required: true
        type: choice
        default: "Landlord invite"
        options:
          - "Landlord invite"

      app_template_1:
        description: "Select application 1 Status, FirstName, LastName, SSN"
        required: true
        type: choice
        default: "Application Submitted, JOSEPH, GILBERT, 666586249"
        options:
          - "Account Created, JOSEPH, GILBERT, 666586249"
          - "Account Created, ERNESTO, FERNANDEZ, 666321789"
          - "Account Created, QMFXC, CTAEQQJR, 666043071"
          - "Account Created, BLZGQG, USYMS, 666024520"
          - "Account Created, NREXTPZU, GDPKXARDI, 666022550"
          - "Uploading Documents, JOSEPH, GILBERT, 666586249"
          - "Uploading Documents, ERNESTO, FERNANDEZ, 666321789"
          - "Uploading Documents, QMFXC, CTAEQQJR, 666043071"
          - "Uploading Documents, BLZGQG, USYMS, 666024520"
          - "Uploading Documents, NREXTPZU, GDPKXARDI, 666022550"
          - "Application Submitted, JOSEPH, GILBERT, 666586249"
          - "Application Submitted, ERNESTO, FERNANDEZ, 666321789"
          - "Application Submitted, QMFXC, CTAEQQJR, 666043071"
          - "Application Submitted, BLZGQG, USYMS, 666024520"
          - "Application Submitted, NREXTPZU, GDPKXARDI, 666022550"

      app_template_2:
        description: "Select application 2 Status, FirstName, LastName, SSN"
        required: true
        type: choice
        default: "Application Submitted, JOSEPH, GILBERT, 666586249"
        options:
          - "Account Created, JOSEPH, GILBERT, 666586249"
          - "Account Created, ERNESTO, FERNANDEZ, 666321789"
          - "Account Created, QMFXC, CTAEQQJR, 666043071"
          - "Account Created, BLZGQG, USYMS, 666024520"
          - "Account Created, NREXTPZU, GDPKXARDI, 666022550"
          - "Uploading Documents, JOSEPH, GILBERT, 666586249"
          - "Uploading Documents, ERNESTO, FERNANDEZ, 666321789"
          - "Uploading Documents, QMFXC, CTAEQQJR, 666043071"
          - "Uploading Documents, BLZGQG, USYMS, 666024520"
          - "Uploading Documents, NREXTPZU, GDPKXARDI, 666022550"
          - "Application Submitted, JOSEPH, GILBERT, 666586249"
          - "Application Submitted, ERNESTO, FERNANDEZ, 666321789"
          - "Application Submitted, QMFXC, CTAEQQJR, 666043071"
          - "Application Submitted, BLZGQG, USYMS, 666024520"
          - "Application Submitted, NREXTPZU, GDPKXARDI, 666022550"

      app_template_3:
        description: "Select application 3 Status, FirstName, LastName, SSN"
        required: true
        type: choice
        default: "-"
        options:
          - "-"
          - "Account Created, JOSEPH, GILBERT, 666586249"
          - "Account Created, ERNESTO, FERNANDEZ, 666321789"
          - "Account Created, QMFXC, CTAEQQJR, 666043071"
          - "Account Created, BLZGQG, USYMS, 666024520"
          - "Account Created, NREXTPZU, GDPKXARDI, 666022550"
          - "Uploading Documents, JOSEPH, GILBERT, 666586249"
          - "Uploading Documents, ERNESTO, FERNANDEZ, 666321789"
          - "Uploading Documents, QMFXC, CTAEQQJR, 666043071"
          - "Uploading Documents, BLZGQG, USYMS, 666024520"
          - "Uploading Documents, NREXTPZU, GDPKXARDI, 666022550"
          - "Application Submitted, JOSEPH, GILBERT, 666586249"
          - "Application Submitted, ERNESTO, FERNANDEZ, 666321789"
          - "Application Submitted, QMFXC, CTAEQQJR, 666043071"
          - "Application Submitted, BLZGQG, USYMS, 666024520"
          - "Application Submitted, NREXTPZU, GDPKXARDI, 666022550"

      app_template_4:
        description: "Select application 4 Status, FirstName, LastName, SSN"
        required: true
        type: choice
        default: "-"
        options:
          - "-"
          - "Account Created, JOSEPH, GILBERT, 666586249"
          - "Account Created, ERNESTO, FERNANDEZ, 666321789"
          - "Account Created, QMFXC, CTAEQQJR, 666043071"
          - "Account Created, BLZGQG, USYMS, 666024520"
          - "Account Created, NREXTPZU, GDPKXARDI, 666022550"
          - "Uploading Documents, JOSEPH, GILBERT, 666586249"
          - "Uploading Documents, ERNESTO, FERNANDEZ, 666321789"
          - "Uploading Documents, QMFXC, CTAEQQJR, 666043071"
          - "Uploading Documents, BLZGQG, USYMS, 666024520"
          - "Uploading Documents, NREXTPZU, GDPKXARDI, 666022550"
          - "Application Submitted, JOSEPH, GILBERT, 666586249"
          - "Application Submitted, ERNESTO, FERNANDEZ, 666321789"
          - "Application Submitted, QMFXC, CTAEQQJR, 666043071"
          - "Application Submitted, BLZGQG, USYMS, 666024520"
          - "Application Submitted, NREXTPZU, GDPKXARDI, 666022550"

      app_template_5:
        description: "Select application 5 Status, FirstName, LastName, SSN"
        required: true
        type: choice
        default: "-"
        options:
          - "-"
          - "Account Created, JOSEPH, GILBERT, 666586249"
          - "Account Created, ERNESTO, FERNANDEZ, 666321789"
          - "Account Created, QMFXC, CTAEQQJR, 666043071"
          - "Account Created, BLZGQG, USYMS, 666024520"
          - "Account Created, NREXTPZU, GDPKXARDI, 666022550"
          - "Uploading Documents, JOSEPH, GILBERT, 666586249"
          - "Uploading Documents, ERNESTO, FERNANDEZ, 666321789"
          - "Uploading Documents, QMFXC, CTAEQQJR, 666043071"
          - "Uploading Documents, BLZGQG, USYMS, 666024520"
          - "Uploading Documents, NREXTPZU, GDPKXARDI, 666022550"
          - "Application Submitted, JOSEPH, GILBERT, 666586249"
          - "Application Submitted, ERNESTO, FERNANDEZ, 666321789"
          - "Application Submitted, QMFXC, CTAEQQJR, 666043071"
          - "Application Submitted, BLZGQG, USYMS, 666024520"
          - "Application Submitted, NREXTPZU, GDPKXARDI, 666022550"

      app_template_6:
        description: "Select application 6 Status, FirstName, LastName, SSN"
        required: true
        type: choice
        default: "-"
        options:
          - "-"
          - "Account Created, JOSEPH, GILBERT, 666586249"
          - "Account Created, ERNESTO, FERNANDEZ, 666321789"
          - "Account Created, QMFXC, CTAEQQJR, 666043071"
          - "Account Created, BLZGQG, USYMS, 666024520"
          - "Account Created, NREXTPZU, GDPKXARDI, 666022550"
          - "Uploading Documents, JOSEPH, GILBERT, 666586249"
          - "Uploading Documents, ERNESTO, FERNANDEZ, 666321789"
          - "Uploading Documents, QMFXC, CTAEQQJR, 666043071"
          - "Uploading Documents, BLZGQG, USYMS, 666024520"
          - "Uploading Documents, NREXTPZU, GDPKXARDI, 666022550"
          - "Application Submitted, JOSEPH, GILBERT, 666586249"
          - "Application Submitted, ERNESTO, FERNANDEZ, 666321789"
          - "Application Submitted, QMFXC, CTAEQQJR, 666043071"
          - "Application Submitted, BLZGQG, USYMS, 666024520"
          - "Application Submitted, NREXTPZU, GDPKXARDI, 666022550"


env:
  JSON_INPUT: ${{ github.event.inputs.movie_as_json }}
      
jobs:
  welcome-to-marvel:
    runs-on: ubuntu-latest
    steps:
      - name: set inputs as variables
        run: |
          echo -e "First_Movie=$(echo $JSON_INPUT | jq ".First_Movie")" >> $GITHUB_ENV
          echo -e "Second_Movie=$(echo $JSON_INPUT | jq ".Second_Movie")" >> $GITHUB_ENV
          echo -e "Third_Movie=$(echo $JSON_INPUT | jq ".Third_Movie")" >> $GITHUB_ENV
          echo -e "Fourth_Movie=$(echo $JSON_INPUT | jq ".Fourth_Movie")" >> $GITHUB_ENV
          echo -e "Fifth_Movie=$(echo $JSON_INPUT | jq ".Fifth_Movie")" >> $GITHUB_ENV
          echo -e "Sixth_Movie=$(echo $JSON_INPUT | jq ".Sixth_Movie")" >> $GITHUB_ENV
          echo -e "Seventh_Movie=$(echo $JSON_INPUT | jq ".Seventh_Movie")" >> $GITHUB_ENV
          echo -e "Eighth_Movie=$(echo $JSON_INPUT | jq ".Eighth_Movie")" >> $GITHUB_ENV
          echo -e "Ninth_Movie=$(echo $JSON_INPUT | jq ".Ninth_Movie")" >> $GITHUB_ENV
          echo -e "Tenth_Movie=$(echo $JSON_INPUT | jq ".Tenth_Movie")" >> $GITHUB_ENV
          echo -e "Eleventh_Movie=$(echo $JSON_INPUT | jq ".Eleventh_Movie")" >> $GITHUB_ENV
          echo -e "Twelfth_Movie=$(echo $JSON_INPUT | jq ".Twelfth_Movie")" >> $GITHUB_ENV
      
      - name: Print movies list
        run: |
          echo "First_Movie= ${{ env.First_Movie }}"
          echo "Second_Movie= ${{ env.Second_Movie }}"
          echo "Third_Movie= ${{ env.Third_Movie }}"
          echo "Fourth_Movie= ${{ env.Fourth_Movie }}"
          echo "Fifth_Movie= ${{ env.Fifth_Movie }}"
          echo "Sixth_Movie= ${{ env.Sixth_Movie }}"
          echo "Seventh_Movie= ${{ env.Seventh_Movie }}"
          echo "Eighth_Movie= ${{ env.Eighth_Movie }}"
          echo "Ninth_Movie= ${{ env.Ninth_Movie }}"
          echo "Tenth_Movie= ${{ env.Tenth_Movie }}"
          echo "Eleventh_Movie= ${{ env.Eleventh_Movie }}"
          echo "Twelfth_Movie= ${{ env.Twelfth_Movie }}"
