name: Run JS script

on:
  schedule:
    - cron: "40 15 * * *"
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Select Environment"
        required: true
        type: choice
        default: "integration"
        options:
          - "staging"
          - "integration"

permissions: write-all

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm i

      - name: Print
        run: env | sort

      - name: Run Playwright Tests
        shell: bash
        run: |
          echo '{
                "runId": "RUN_TOKEN",
                "action": "getTestList",
                "args": {
                  "environment": "environment",
                  "limitTests": "testCaseIdentifiers",
                  "slackChannel": "slackChannel",
                  "createTestRunInTestRail": "createTestRunInTestRail",
                  "reportTitle": "reportTitle",
                  "statusAutoinvite": "statusAutoinvite",
                  "dispatchParams": "dispatchParams"
                }
              }'

      - name: Run Script
        run: |
          echo ${{ inputs.environment_name }}
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
          echo ${{ secrets.TOKEN }}
          echo ${{ secrets.github_token }}

          ENV=${{ inputs.environment_name }} REPO_OWNER=${{ github.repository_owner }} REPO_NAME=${{ github.repository }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} node src/index.js
