name: Automation
on:
  schedule:
    - cron: "30 15 * * *"
    - cron: "40 15 * * *"
    - cron: "50 15 * * *"
    - cron: "00 16 * * *"
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Select Environment"
        required: true
        type: choice
        default: "staging"
        options:
          - "staging"
          - "integration"
      test_tag:
        description: "Run a group: 'monolith-nightly-group'"
        required: true
        type: choice
        default: "monolith-nightly"
        options:
          - "monolith-nightly"
          - "monolith-nightly-group-1"
          - "monolith-nightly-group-2"
          - "monolith-nightly-group-3"
          - "monolith-nightly-group-4"
      enable_testrail:
        description: "Enable TestRail"
        required: true
        type: boolean
        default: false

permissions: write-all

jobs:
  monolith_nightly:
    name: IQuality Monolith Nightly Tests
    runs-on: ubuntu-latest
    env:
      TEST_TAG: ${{ inputs.test_tag }}
      ENVIRONMENT_NAME: ${{ inputs.environment_name  || 'staging' }}
    environment: ${{ env.ENVIRONMENT_NAME }}
    steps:
      - name: Set "Group 1" env on schedule
        if: github.event.schedule == '00 06 * * *'
        run: echo "TEST_TAG=monolith-nightly-group-1" >> $GITHUB_ENV

      - name: Set "Group 2" env on schedule
        if: github.event.schedule == '10 06 * * *'
        run: echo "TEST_TAG=monolith-nightly-group-2" >> $GITHUB_ENV

      - name: Set "Group 3" env on schedule
        if: github.event.schedule == '20 06 * * *'
        run: echo "TEST_TAG=monolith-nightly-group-3" >> $GITHUB_ENV

      - name: Set "Group 4" env on schedule
        if: github.event.schedule == '30 06 * * *'
        run: echo "TEST_TAG=monolith-nightly-group-4" >> $GITHUB_ENV

      - name: Print Env list
        run: env | sort

      - name: Invoke AWS Step Function
        run: |
          echo "Monolith Nightly Test Run (${{ env.TEST_TAG }})"
          echo "runTokenPrefix: ${{ env.TEST_TAG }}"
          echo "environment: ${{ env.ENVIRONMENT_NAME }}"
          echo "testCaseIdentifiers: '[@${{ env.TEST_TAG }}]'"
          echo "slackChannel: tech_qa_monolith"
