name: Run JS script

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Select Environment"
        required: true
        type: choice
        default: "integration"
        options:
          - "staging"
          - "integration"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm i

      - name: Run Script
        run: |
          echo ${{ inputs.environment_name }}
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}

          node index.js ${{ inputs.environment_name }}